src/Entity/Day.php
<?php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
class Day
{
    private $day_id;
    private $training_id;
    private $exercise_id;
    private $set_id;
    private $creation_date;
    private $finish_date;
    private $main_time;
    private $user_id;
    private $deleted;
    public function getDayId(): ?int
    {
        return $this->day_id;
    }
    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }
    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;
        return $this;
    }
    public function getFinishDate(): ?\DateTimeInterface
    {
        return $this->finish_date;
    }
    public function setFinishDate(?\DateTimeInterface $finish_date): self
    {
        $this->finish_date = $finish_date;
        return $this;
    }
    public function getMainTime(): ?string
    {
        return $this->main_time;
    }
    public function setMainTime(?string $main_time): self
    {
        $this->main_time = $main_time;
        return $this;
    }
    public function getTrainingId(): ?Training
    {
        return $this->training_id;
    }
    public function setTrainingId(?Training $training_id): self
    {
        $this->training_id = $training_id;
        return $this;
    }
    public function getExerciseId(): ?Exercise
    {
        return $this->exercise_id;
    }
    public function setExerciseId(?Exercise $exercise_id): self
    {
        $this->exercise_id = $exercise_id;
        return $this;
    }
    public function getSetId(): ?Set
    {
        return $this->set_id;
    }
    public function setSetId(?Set $set_id): self
    {
        $this->set_id = $set_id;
        return $this;
    }
    public function getUserId(): ?User
    {
        return $this->user_id;
    }
    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;
        return $this;
    }
    public function getDeleted(): ?bool
    {
        return $this->deleted;
    }
    public function setDeleted(bool $deleted): self
    {
        $this->deleted = $deleted;
        return $this;
    }
}

src/Controller/DayController.php
<?php

namespace App\Controller;

use App\Entity\Day;
use App\Entity\User;
use App\Repository\DayRepository;
use App\Repository\ExerciseRepository;
use App\Repository\SetRepository;
use App\Repository\TrainingRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Forms;
use Symfony\Component\HttpFoundation\Request;
use Tarantool\Mapper\Repository;

class DayController extends Controller
{
    /** @var DayRepository */
    private $dayRepository;

    /** @var TrainingRepository */
    private $trainigRepository;

    /** @var EntityManager*/
    private $em;

    /** @var UserRepository */
    private $userRepository;

    /** @var ExerciseRepository */
    private $exerciseRepository;

    /** @var SetRepository */
    private $setRepository;

    /**
     * @return SetRepository
     */
    public function getSetRepository(): SetRepository
    {
        return $this->setRepository;
    }

    /**
     * @param SetRepository $setRepository
     * @return self
     */
    public function setSetRepository(SetRepository $setRepository): self
    {
        $this->setRepository = $setRepository;
        return $this;
    }

    /**
     * @return ExerciseRepository
     */
    public function getExerciseRepository(): ExerciseRepository
    {
        return $this->exerciseRepository;
    }

    /**
     * @param ExerciseRepository $exerciseRepository
     * @return self
     */
    public function setExerciseRepository(ExerciseRepository $exerciseRepository): self
    {
        $this->exerciseRepository = $exerciseRepository;
        return $this;
    }
    /**
     * @return UserRepository
     */
    public function getUserRepository(): EntityRepository
    {
        return $this->userRepository;
    }

    /**
     * @param UserRepository $userRepository
     * @return self
     */
    public function setUserRepository(EntityRepository $userRepository): self
    {
        $this->userRepository = $userRepository;
        return $this;
    }

    /**
     * @return TrainingRepository
     */
    public function getTrainigRepository(): TrainingRepository
    {
        return $this->trainigRepository;
    }

    /**
     * @param TrainingRepository $trainigRepository
     * @return self
     */
    public function setTrainigRepository(TrainingRepository $trainigRepository): self
    {
        $this->trainigRepository = $trainigRepository;
        return $this;
    }

    /**
     * @return DayRepository
     */
    public function getDayRepository()
    {
        return $this->dayRepository;
    }

    /**
     * @param mixed $dayRepository
     * @return self
     */
    public function setDayRepository($dayRepository): self
    {
        $this->dayRepository = $dayRepository;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getEm(): EntityManager
    {
        return $this->em;
    }

    /**
     * @param $em
     * @return self
     */
    public function setEm($em): self
    {
        $this->em = $em;
        return $this;
    }

    public function __construct(EntityManagerInterface $em)
    {
        $this->setEm($em)
            ->setDayRepository($this->em->getRepository('App:Day'))
            ->setTrainigRepository($this->em->getRepository('App:Training'))
            ->setUserRepository($this->em->getRepository('App:User'))
            ->setExerciseRepository($this->em->getRepository('App:Exercise'))
            ->setSetRepository($this->em->getRepository('App:Set'))
        ;
    }

    public function index()
    {
            $grid = $this->getTrainigRepository()->findBy([
                'user_id' => $this->getUser(),
                'deleted' => false
            ]);

            return $this->render('day/index.html.twig', [
                'controller_name' => 'DayController',
                'grid'            => $grid,
                'is_training' => $this->getUser()->getDayId()
            ]);
    }

    public function started($training_id)
    {
        if (is_null($this->getUser()->getDayId())) {
            $training = $this->getTrainigRepository()->findOneBy(['training_id' => $training_id]);
            $this->updateUsersDay($this->getUser(), $training);
        }

        /** @var Day $day */
        $day = $this->getDayRepository()->findOneBy([
            'day_id' => $this->getUser()->getDayId()
        ]);

        $grid = $this->getEm()->getConnection()->createQueryBuilder()
            ->select('e.*')
            ->from('exercise', 'e')
            ->leftJoin('e', 'trainings', 't', 't.exercise_id=e.exercise_id')
            ->where('e.deleted=false')
            ->andWhere('t.training_id=:training')
            ->setParameter('training',$training_id)
            ->execute()
            ->fetchAll()
        ;

        return $this->render('day/day.html.twig', [
            'controller_name' => 'DayController',
            'grid' => $grid,
            'day' => $day,
            'is_training' => $this->getUser()->getDayId()
        ]);
    }

    /** Создаём  и возвращаем id тренировочного дня */
    public function updateUsersDay($user, $training)
    {
        try {
            $day = new Day();
            $day->setUserId($user)
                ->setCreationDate(
                    \DateTime::createFromFormat(
                        \DateTimeInterface::W3C,
                        date(\DateTimeInterface::W3C)
                    )
                )
                ->setTrainingId($training)
                ->setDeleted(false)
            ;
            $this->getEm()->persist($day);
            $this->getEm()->flush();

            /** @var User $user */
            $user = $this->getUser();
            $user->setDayId($day);

            $this->getEm()->persist($user);
            $this->getEm()->flush();
        } catch (\Exception $e) {
            return false;
        }

        return true;
    }

    public function exercise($day_id, $exrcise_id, $training_id, Request $request)
    {
        $exerciseEntity = $this->getExerciseRepository()->findOneBy(['exercise_id' => $exrcise_id]);
        $result = null;
        $formFactory = Forms::createFormFactoryBuilder()
            ->getFormFactory();

        $form = $formFactory->createBuilder(
            FormType::class,null, [
                'action' => "/day_exercise/$day_id/$training_id/$exrcise_id/",
                'method' => 'POST'
            ]
        )
            ->add("tries", TextType::class, [
                'attr' => [
                    'value' => (integer)$request->get("form")["tries"] ?? 0,
                    'inputmode' => 'numeric',
                    'pattern'   => '[0-9]*',
                    'class' => 'form-control'
                ]
            ])
            ->add("weight", TextType::class, [
                'attr' => [
                    'value' => (integer)$request->get("form")["weight"] ?? 0,
                    'inputmode' => 'numeric',
                    'pattern'   => '[0-9]*',
                    'class' => 'form-control'
                ]
            ])
            ->add("comment", TextareaType::class, [
                'required' =>false,
                'attr' => ['class' => 'form-control']
            ])
            ->getForm();

        $day = $this->getDayRepository()->findOneBy(['day_id' => $day_id]);

        $view = $form->createView();
        $form->handleRequest();

        if ($form->isSubmitted()) {
            $data = $form->getData();
            $result = $this
                ->getSetRepository()
                ->saveSet(
                    $data['comment'],
                    $data['tries'],
                    $data['weight'],
                    $exerciseEntity,
                    $this->getUser(),
                    $day
                );
        }

        $grid = $this->getSetRepository()->findBy([
            'user_id'       => $this->getUser()->getUserId(),
            'exercise_id'   => $exrcise_id,
            'day_id'        => $day,
            'deleted'       => false
        ]);

        $user_id = $this->getUser()->getUserId();

        /** Получаем все подходы в ближайшем тренировочном дне, id которого меньше актуального; в этом упражнении, у этого пользователя */
        $lastTraining = $this->getEm()->getConnection()
            ->query("
                SELECT s.*, max(s.day_id) as day_max
                FROM set s
                WHERE s.user_id = $user_id
                  AND s.exercise_id = $exrcise_id
                  and s.day_id = (
                       SELECT max(s.day_id)
                       FROM set s
                       WHERE s.day_id < $day_id
                )
                group by s.set_id, s.day_id;
            ")
            ->fetchAll()
        ;

        return $this->render('day/day_sets.html.twig', [
            'controller_name' => 'DayController',
            'grid'            => $grid,
            'form'            => $view,
            'result'          => $result,
            'is_training' => $this->getUser()->getDayId(),
            'training' => $training_id,
            'sets' => $lastTraining
        ]);
    }

    public function trainingFinish($day_id)
    {
        $tarantool = $this->get("tarantool.wrap");

        /** @var Day $day */
        $day = $this->getDayRepository()->findOneBy(['day_id' => $day_id]);

        $message = $this->getDayRepository()->updateAndCloseDay($day, $this->getUser());

        /** @var Repository $repository */
        $repository = $tarantool->getMapper()->getRepository('user_last_training_day');

templates/day/day.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% trans %}Training day{% endtrans %}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans %}Choose the exercise to begin a set{% endtrans %}</h4>
                </div>
                <div class="card-body">
                    {% for row in grid %}
                        <div class="row">
                            <div class="margin col">
                                <a href="{{ path('day_exercise', {'day_id': day.dayId, 'training_id':day.getTrainingId.getTrainingId, 'exrcise_id':row.exercise_id}) }}"
                                   class="btn btn-lg btn-success btn-block"
                                   role="button">{{ row.exercise_name }}</a>
                            </div>
                        </div>
                    {% else %}
                        {% trans %}No exercise have been found{% endtrans %}.
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container">
            <div class="row">
                <a href="/" class="margin btn btn-secondary btn-block">{% trans %}Back{% endtrans %}</a>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col"><a class="btn btn-danger margin " href="{{ path('training_finish', {'day_id': day.dayId}) }}">{% trans %}Close training day{% endtrans %}</a></div>
        </div>
    </div>
{% endblock %}

templates/day/day_sets.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Sets{% endtrans %}{% endblock %}

{% block body %}
    <div class="container">
        <div class="accordion" id="accordionExample" style="font-size: 10px">
            <div class="card">
                <div class="card-header" id="headingTwo">
                    <h5 class="mb-0">
                        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            {% trans %}Last training{% endtrans %}
                        </button>
                    </h5>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{% trans %}Weight{% endtrans %}</th>
                                <th scope="col">{% trans %}Tries{% endtrans %}</th>
                                <th scope="col">{% trans %}Time{% endtrans %}</th>
                            </tr>
                            </thead>
                            {% for row in sets %}
                                <tbody>
                                <tr>
                                    <th scope="row">{{ row['set_id'] }}</th>
                                    <td>{{ row['weight'] }}</td>
                                    <td>{{ row['tries'] }}</td>
                                    <td>{{ row['last_update_date'] }}</td>
                                </tr>
                                </tbody>
                            {% else %}
                                {% trans %}No sets have been found{% endtrans %}.
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>

        {% if grid is not empty %}
            <div class="row">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            {% trans %}Sets{% endtrans %}
                        </div>
                        <div class="card-body">
                            <table class="table table-striped table-dark">
                                <thead>
                                <tr>
                                    <th scope="col">{% trans %}Count of tries{% endtrans %}</th>
                                    <th scope="col">{% trans %}Weight{% endtrans %}</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for i in 0 .. grid | length -1 %}
                                <tr>
                                    <td>{{ grid[i].getTries }} </td>
                                    <td>{{ grid[i].weight }}  {% trans %}kg{% endtrans %}</td>
                                </tr>
                                {% else %}
                                    {% trans %}No sets have been found{% endtrans %}.
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
            </div>
        {% endif %}
        </div>
        <div class="container">
            <div class="row card">
                <div class="card-header">
                    <h3>{% trans %}Add new set{% endtrans %}</h3>
                </div>
                {{ form_start(form) }}
                <div class="col">
                    <div class="margin">
                        {{ form_label(form.tries) }}
                        {{ form_widget(form.tries) }}
                    </div>
                    <div class="margin">
                        {{ form_label(form.weight) }}
                        {{ form_widget(form.weight) }}
                    </div>
                    <div class="margin">
                        {{ form_label(form.comment) }}
                        {{ form_widget(form.comment) }}
                    </div>
                    <input class="margin btn btn-primary" type="submit" />
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
        <div class="container" style="margin-bottom: 100px">
            <div class="row">
                <a href="{{ path('day_started', {'training_id' : training}) }}" class="margin btn btn-secondary btn-block">{% trans %}Back{% endtrans %}</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/day/finish.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% trans %}Training is finished{% endtrans %}!{% endblock %}
{% block body %}
    <div class="container">
        <div class="card margin">
            <div class="card-header">
                <h2>{% trans %}Training is finished{% endtrans %}!</h2>
            </div>
            <div class="card-body">
                {% if message is defined %}
                    {{ message }}
                {%  endif %}
            </div>
        </div>

        <div class="container">
            <div class="row">
                <a href="{{ path('auth') }}" class="margin btn btn-secondary btn-block">{% trans %}Back{% endtrans %}</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/day/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}{% trans %}Training day{% endtrans %}{% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <h4>{% trans %}Choose the training to begin an exercise{% endtrans %}</h4>
                </div>
                <div class="card-body" style="word-break: break-all;">
                    {% for row in grid %}
                        <div class="row">
                            <div class="margin col">
                                <a href="{{ path('day_started', {'training_id': row.getTrainingId}) }}"
                                   class="btn btn-lg btn-success btn-block"
                                   role="button">{{ row.getTrainingName }}</a>
                            </div>
                        </div>
                    {% else %}
                        {% trans %}No trainings have been found{% endtrans %}.
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <a href="/" class="margin btn btn-secondary btn-block">{% trans %}Back{% endtrans %}</a>
            </div>
        </div>

    </div>
{% endblock %}